using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace AssertShimGenerator
{
    /// <summary>
    /// Emits a class of ordinary instance methods forwarding to every extension method on
    /// AnyUnit's <c>IAssert</c>.
    /// </summary>
    /// <remarks>
    /// C# will not dispatch an extension method when an argument is <c>dynamic</c> (CS1973),
    /// which is most of this suite, since what it tests is dynamic. An instance method on a
    /// statically typed receiver has no such problem. Rather than hand-write the forwarding,
    /// find it: every <c>static ... M(this IAssert ...)</c> reachable from the compilation.
    /// </remarks>
    [Generator]
    public class ClassicAssertGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var source = context.CompilationProvider.Select((compilation, _) => Emit(compilation));
            context.RegisterSourceOutput(source, (spc, text) => spc.AddSource("ClassicAssert.g.cs", text));
        }

        private static string Emit(Compilation compilation)
        {
            var iassert = compilation.GetTypeByMetadataName("AnyUnit.IAssert");
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> by AssertShimGenerator.");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("namespace UnitTestImpromptuInterface");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Instance methods over AnyUnit's IAssert extensions, so a `dynamic` argument binds (CS1973).</summary>");
            sb.AppendLine("    public partial class ClassicAssert");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly AnyUnit.IAssert _assert;");
            sb.AppendLine("        public ClassicAssert(AnyUnit.IAssert assert) { _assert = assert; }");

            if (iassert != null)
            {
                // IAssert's own members first: the wrapper stands in for Assert entirely, and
                // Fail/Ignore/True/False are instance members, not extensions.
                foreach (var m in iassert.GetMembers().OfType<IMethodSymbol>())
                {
                    if (m.MethodKind != MethodKind.Ordinary || m.Name == "Equals") continue;
                    sb.AppendLine(Forward(m, instance: true));
                }

                foreach (var m in Forwardable(compilation, iassert))
                    sb.AppendLine(Forward(m, instance: false));
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Every extension method on IAssert, from this compilation and its references.</summary>
        private static IEnumerable<IMethodSymbol> Forwardable(Compilation compilation, INamedTypeSymbol iassert)
        {
            var seen = new HashSet<string>();
            var assemblies = new[] { compilation.Assembly }
                .Concat(compilation.SourceModule.ReferencedAssemblySymbols);

            foreach (var assembly in assemblies)
            foreach (var type in Types(assembly.GlobalNamespace))
            {
                if (!type.MightContainExtensionMethods) continue;

                foreach (var m in type.GetMembers().OfType<IMethodSymbol>())
                {
                    if (!m.IsExtensionMethod ||
                        m.DeclaredAccessibility != Accessibility.Public ||
                        !SymbolEqualityComparer.Default.Equals(m.Parameters.FirstOrDefault()?.Type, iassert))
                        continue;

                    // One overload per shape; distinct arities and parameter types, first wins.
                    var key = m.Name + "`" + m.Arity + "(" + string.Join(",", m.Parameters.Skip(1).Select(p => p.Type.ToDisplayString())) + ")";
                    if (seen.Add(key)) yield return m;
                }
            }
        }

        private static IEnumerable<INamedTypeSymbol> Types(INamespaceSymbol ns)
        {
            foreach (var t in ns.GetTypeMembers()) yield return t;
            foreach (var child in ns.GetNamespaceMembers())
            foreach (var t in Types(child)) yield return t;
        }

        private static string Forward(IMethodSymbol m, bool instance)
        {
            var ps = (instance ? m.Parameters : m.Parameters.Skip(1)).ToList();

            string Ref(IParameterSymbol p)
            {
                switch (p.RefKind)
                {
                    case RefKind.Ref: return "ref ";
                    case RefKind.Out: return "out ";
                    case RefKind.In: return "in ";
                    default: return "";
                }
            }

            string Decl(IParameterSymbol p)
            {
                var prefix = p.IsParams ? "params " : Ref(p);
                var suffix = p.HasExplicitDefaultValue ? " = " + Default(p) : "";
                return prefix + p.Type.ToDisplayString() + " " + Escape(p.Name) + suffix;
            }

            var typeParams = m.IsGenericMethod
                ? "<" + string.Join(", ", m.TypeParameters.Select(t => t.Name)) + ">"
                : "";
            var constraints = string.Concat(m.TypeParameters.Select(Constraint));
            var returns = m.ReturnsVoid ? "void" : m.ReturnType.ToDisplayString();
            // Called in static form through the declaring type, so the generated file needs no
            // using directives - and cannot be broken by one the consumer removes.
            var passed = ps.Select(p => Ref(p) + Escape(p.Name));
            var args = string.Join(", ", instance ? passed : new[] { "_assert" }.Concat(passed));
            var body = instance
                ? "_assert." + m.Name + typeParams + "(" + args + ")"
                : m.ContainingType.ToDisplayString() + "." + m.Name + typeParams + "(" + args + ")";
            return "        public " + returns + " " + m.Name + typeParams + "(" + string.Join(", ", ps.Select(Decl)) + ")" + constraints + "\n" +
                   "            => " + body + ";";
        }

        /// <summary>The `where T : ...` clause, without which a constrained forward will not compile.</summary>
        private static string Constraint(ITypeParameterSymbol t)
        {
            var parts = new List<string>();
            if (t.HasReferenceTypeConstraint) parts.Add("class");
            if (t.HasValueTypeConstraint) parts.Add("struct");
            parts.AddRange(t.ConstraintTypes.Select(c => c.ToDisplayString()));
            if (t.HasConstructorConstraint) parts.Add("new()");
            return parts.Count == 0 ? "" : " where " + t.Name + " : " + string.Join(", ", parts);
        }

        private static string Default(IParameterSymbol p)
        {
            var v = p.ExplicitDefaultValue;
            if (v == null) return "default";
            if (v is string s) return SymbolDisplay.FormatLiteral(s, true);
            if (v is bool b) return b ? "true" : "false";
            return SymbolDisplay.FormatPrimitive(v, true, false);
        }

        private static string Escape(string name) =>
            SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;
    }
}
