name: Build .net core

on: [push]

jobs:
  build:
    name: Test ${{ matrix.os }} for dotnet ${{ matrix.dotnet }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: [ '8.0.x' ]
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet core
      run: dotnet build --configuration Release
    - name: Tests
      run: dotnet test Tests/UnitTestImpromptuInterface/UnitTestImpromptuInterface.csproj --configuration Release --no-build --no-restore --filter=TestCategory!=Performance